### ISSUE TITLE
Domain argument passing fails when adding -c flag

### ISSUE THREAD

**Issue by sdcloudt** [mkorthof/freenom-script#12] opened 2019-08-14 20:54 UTC
When i try to run:

```
freenom.sh -c /etc/freenom.conf -u example.com
```
It will return `Error: invalid domain name "/etc/freenom.confexample.com"`.

I debugged the code and I think it occurs at line 130. That line should remove the `-c arg` part from the arguments list. The `sed` command misses the `/` character to remove and therefore the entire `-c` clause is not removed. However, when I add that `/` character, it will recognize all arguments as one big `-c arg`, which results in also removing `-u arg` part.

I cannot seem to find a quickfix solution but to rewrite the argument parsing to something as used in this:
[https://stackoverflow.com/questions/192249/how-do-i-parse-command-line-arguments-in-bash]()

**Comment by mkorthof** [comment] 2019-08-20 21:01
Thank you for your suggestion, there are a number of ways to handle arguments  in a bash script (besides getops). Each with its own (dis)advantages.

I was unable to reproduce your issue though:

```
$ echo "-c /etc/freenom.sh" | sed -E 's/ ?-c [][a-zA-Z0-9 !"#$%&'\''()*+,-.:;<=>?@^_`{}~.]+ ?//g'


```

```
~/src/freenom-script [git:master* u=]$ freenom.sh -c /tmp/freenom.conf -u example.com
DEBUG: conf scriptConf=/tmp/freenom.conf
Error: Logfile "/var/log/freenom.log" not writable, using "/tmp/freenom.log" instead
DEBUG: getDomArgs d_args=-u example.com arg_domain_name=example.com arg_domain_id= arg_subdomain_name=
DEBUG: args 1=-c 2=/tmp/freenom.conf 3=-u 4=example.com 5= 6=
DEBUG: opts/conf freenom_out_dir=/var/log freenom_out_mask=freenom out_path=/tmp/freenom
DEBUG: opts/conf freenom_domain_name=example.com freenom_domain_id= freenom_subdomain_name=
^C
```

Tests passed too:

```
~/src/freenom-script/test [git:master* u=]$ bats freenom-args.bats -f conf
 ✓ freenom.sh -c /usr/local/bin/freenom.conf
 ✓ freenom.sh -c /invalid/invalid.conf
```

I did change the regex, not sure it it fixes anything for you. 
In case the issue persists please enable debug and paste the output.

**Comment by sdcloudt** [comment] 2019-08-21 10:13
Thank you for your reply.

First of all:
sed: GNU sed 4.7
bash: GNU bash 5.0.3

When I reproduced the bug using:
```
$ echo "-c /etc/freenom.sh" | sed -E 's/ ?-c [][a-zA-Z0-9 !"#$%&'\''()*+,-.:;<=>?@^_`{}~.]+ ?//g'
```
The output was: `-c /etc/freenom.sh`

Here is the debug output when using both `-c` and `-u`:

```
$ ./freenom.sh -c /usr/local/src/freenom-script/freenom.conf -u example.com
DEBUG: conf scriptConf=/usr/local/src/freenom-script/freenom.conf
Error: Logfile "/var/log/freenom.log" not writable, using "/tmp/freenom.log" instead
DEBUG: getDomArgs d_args=-c /usr/local/src/freenom-script/freenom.conf -u example.com arg_domain_name=/usr/local/src/freenom-script/freenom.confexample.com arg_domain_id= arg_subdomain_name=cript/freenom.conf
Error: invalid domain name "/usr/local/src/freenom-script/freenom.confexample.com"
```
Another case using relative directories for `-c `:
```
$ ./freenom.sh -c freenom.conf -u example.com
DEBUG: conf scriptConf=freenom.conf
Error: Logfile "/var/log/freenom.log" not writable, using "/tmp/freenom.log" instead
DEBUG: getDomArgs d_args= arg_domain_name= arg_domain_id= arg_subdomain_name=
Error: Domain Name missing
  Try: freenom.sh [-u|-r|-z] [domain]
```

I would like to ask you which version of bash and sed you use?

**Comment by sdcloudt** [comment] 2019-08-22 09:40
On my other system running:
GNU sed 4.7
BASH 5.0.7(1)

I get the same errors.

**Comment by sdcloudt** [comment] 2019-08-22 12:54
So I created a version using getopts. I tested it on my own machines but was unfortenately not able to run the unit tests because they depend on certain system specific aspect such as file locations.

By using getopts my bug does not occur anymore. Furthermore, it is now possible to escape options using `"` without any problem.

**Comment by mkorthof** [comment] 2019-08-31 12:31
Seems there's indeed an issue with that regex on newer sed versions.
It works fine on e.g. sed 4.4 (+bash 4.4.12) but not on sed 4.7 (bash 5.0.3).

Its fixed in the next version, or if you want you can try the attached patch.
I've also added a few tests to detect stuff like this.

Thanks for looking into this and your PR 👍


[freenom.patch.txt](https://github.com/mkorthof/freenom-script/files/3562448/freenom.patch.txt)

**Closed as completed by mkorthof** 2019-08-31 12:31 UTC
Labels: question
